# Generated by Django 5.0.7 on 2025-10-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('guest_house', 'Guest House'), ('resort', 'Resort'), ('hostel', 'Hostel'), ('cottage', 'Cottage'), ('cabin', 'Cabin'), ('luxury_suite', 'Luxury Suite')], default='hotel', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
